// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmOlLAm1-kJtmSC5LKqGwQbfJupWGjKxI',
    appId: '1:553459087272:web:965a05b11ecdeca8578f9d',
    messagingSenderId: '553459087272',
    projectId: 'stockscreener-dc9df',
    authDomain: 'stockscreener-dc9df.firebaseapp.com',
    storageBucket: 'stockscreener-dc9df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN17Je2bkyDJIZaGN_K9opV0YzWfsBZaI',
    appId: '1:553459087272:android:69fb5322daa458f1578f9d',
    messagingSenderId: '553459087272',
    projectId: 'stockscreener-dc9df',
    storageBucket: 'stockscreener-dc9df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiMIcNWeO7v-58u0zHgBfzxoX-H0aOsPI',
    appId: '1:553459087272:ios:ed947df3ee7a987a578f9d',
    messagingSenderId: '553459087272',
    projectId: 'stockscreener-dc9df',
    storageBucket: 'stockscreener-dc9df.firebasestorage.app',
    iosBundleId: 'com.example.sneakerPuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiMIcNWeO7v-58u0zHgBfzxoX-H0aOsPI',
    appId: '1:553459087272:ios:ed947df3ee7a987a578f9d',
    messagingSenderId: '553459087272',
    projectId: 'stockscreener-dc9df',
    storageBucket: 'stockscreener-dc9df.firebasestorage.app',
    iosBundleId: 'com.example.sneakerPuma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmOlLAm1-kJtmSC5LKqGwQbfJupWGjKxI',
    appId: '1:553459087272:web:33dc7ee9539aca74578f9d',
    messagingSenderId: '553459087272',
    projectId: 'stockscreener-dc9df',
    authDomain: 'stockscreener-dc9df.firebaseapp.com',
    storageBucket: 'stockscreener-dc9df.firebasestorage.app',
  );
}
